<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<OutputType>Exe</OutputType>
	<TargetFramework>net8.0</TargetFramework>
	<Nullable>enable</Nullable>
	<ImplicitUsings>enable</ImplicitUsings>
	<AssemblyName>ChessBot.MatchRunner</AssemblyName>
	<RootNamespace>ChessBot.MatchRunner</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
	<ProjectReference Include="..\ChessBot.Engine\ChessBot.Engine.csproj" />
  </ItemGroup>

</Project>
